// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu8JcyF8503yuuLzKmrUGPwn2Sg0v2L3s',
    appId: '1:121776647440:web:313c2eda7a4f14b9098995',
    messagingSenderId: '121776647440',
    projectId: 'hsh-personal-homepage',
    authDomain: 'hsh-personal-homepage.firebaseapp.com',
    storageBucket: 'hsh-personal-homepage.firebasestorage.app',
    measurementId: 'G-JQCD73RF9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYhNZ6C1STc8fdRdU1sdlHjakEQaoBXYk',
    appId: '1:121776647440:android:a87b920f649411b4098995',
    messagingSenderId: '121776647440',
    projectId: 'hsh-personal-homepage',
    storageBucket: 'hsh-personal-homepage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1fmCjFaRNGlF13A4_5eG9b3hCMDQVkEQ',
    appId: '1:121776647440:ios:b77c884b186e89d5098995',
    messagingSenderId: '121776647440',
    projectId: 'hsh-personal-homepage',
    storageBucket: 'hsh-personal-homepage.firebasestorage.app',
    iosBundleId: 'com.example.homeSweetHome1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1fmCjFaRNGlF13A4_5eG9b3hCMDQVkEQ',
    appId: '1:121776647440:ios:b77c884b186e89d5098995',
    messagingSenderId: '121776647440',
    projectId: 'hsh-personal-homepage',
    storageBucket: 'hsh-personal-homepage.firebasestorage.app',
    iosBundleId: 'com.example.homeSweetHome1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu8JcyF8503yuuLzKmrUGPwn2Sg0v2L3s',
    appId: '1:121776647440:web:2a1725e04f72e7a6098995',
    messagingSenderId: '121776647440',
    projectId: 'hsh-personal-homepage',
    authDomain: 'hsh-personal-homepage.firebaseapp.com',
    storageBucket: 'hsh-personal-homepage.firebasestorage.app',
    measurementId: 'G-WTJJCLY7LM',
  );
}
